services:
  otp-graph-builder:
    image: opentripplanner/opentripplanner
    container_name: otp-warsaw-graph-builder
    command: java -Xmx10G -jar /otp.jar --build --save
    volumes:
    - ./data:/var/opentripplanner
    # graph-builder runs, creates graph.obj in ./data, then exits (no restart)

  otp-app:
    image: opentripplanner/opentripplanner
    container_name: otp-warsaw-app
    command: java -Xmx10G -jar /otp.jar --load --serve
    volumes:
    - ./data:/var/opentripplanner
    ports:
    - '8080:8080'
    depends_on:
    - otp-graph-builder
    restart: unless-stopped